# Generated by Django 5.1 on 2024-10-07 13:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salt_composition', models.TextField(blank=True, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('manufacturer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_desc', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('drug_interactions', models.TextField(blank=True, null=True)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('short_composition1', models.TextField(blank=True, null=True)),
                ('short_composition2', models.TextField(blank=True, null=True)),
                ('pack_size_label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('results', models.FileField(upload_to='lab_results/')),
                ('date', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(default='0', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthcare_app.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(default='Not provided', max_length=30)),
                ('last_name', models.CharField(default='Not provided', max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(default='notprovided@example.com', max_length=254)),
                ('phone_number', models.CharField(default='Not provided', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(default='Not provided')),
                ('city', models.CharField(default='Not provided', max_length=30)),
                ('state', models.CharField(default='Not provided', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_sugar_fasting', models.FloatField(blank=True, null=True)),
                ('blood_sugar_postprandial', models.FloatField(blank=True, null=True)),
                ('cholesterol_ldl', models.FloatField(blank=True, null=True)),
                ('cholesterol_hdl', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
