# Generated by Django 5.1 on 2024-10-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtodotask',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationtodotask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtodotask',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtodotask',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtodotask',
            name='medication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
