# Generated by Django 5.1 on 2024-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='fixed_user_id',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
