# Generated by Django 5.1 on 2024-10-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare_app', '0002_remove_personalinformation_fixed_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='pack_size_label',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='type',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='drug_interactions',
            new_name='indication',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='is_discontinued',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicine_desc',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='salt_composition',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='short_composition1',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='short_composition2',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='side_effects',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtask',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtask',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtask',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
