# Generated by Django 5.1 on 2024-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare_app', '0003_rename_pack_size_label_medication_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='indication',
            new_name='drug_interactions',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='category',
            new_name='pack_size_label',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='classification',
            new_name='salt_composition',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='dosage_form',
            new_name='short_composition1',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='strength',
            new_name='short_composition2',
        ),
        migrations.AddField(
            model_name='medication',
            name='is_discontinued',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
